### ISSUE TITLE
issue with empty response

### ISSUE THREAD

**Issue by tobsn** [websperts/tinypng-cli#9]
I just ran over 498 files - around half of them returned a JSON parse error and wrote 0 byte files... within 3 seconds of execution (1gbit/400mbit line here, it goes fast) - I now have to reset the repository of those images ;)

**Comment by rasshofer** [comment]
Ooops, sorry for this malfunction! 🙈  I hopefully fixed such issues within 85aecd1 and published a new release (v0.0.6) some minutes ago. Please let us know in case you still have any problems with the new version.
